image: cirrusci/flutter:dev

before_script:
  - echo "$keybase64" > ./keybase64
  - mkdir -p /builds/testapp-system/testapp-flutter/android/app/android/app/
  - base64 -d ./keybase64 > /builds/testapp-system/testapp-flutter/android/app/android/app/key.jks
  - echo "$KEYPROPERTIES" > ./android/key.properties
  - export VERSION=$(cat pubspec.yaml | grep version | awk '{ print $2 }' | cut -f1 -d "+")

stages:
  - build
  - deploy


cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - build/web/

build:apk:
  stage: build
  script:
    - set +o pipefail
    - flutter build apk
    - set -o pipefail
    - mv build/app/outputs/apk/release/app-release.apk xournalpp-mobile-$VERSION.apk
  artifacts:
    paths:
      - xournalpp-mobile-*.apk

build:bundle:
  stage: build
  script:
    - flutter build appbundle
    - mv build/app/outputs/bundle/release/app-release.aab xournalpp-mobile-$VERSION.aab
  artifacts:
    paths:
      - xournalpp-mobile-*.aab

build:web:
  stage: build
  script:
    - flutter config --enable-web
    - flutter pub get
    - set +o pipefail
    - flutter build web #--dart-define=FLUTTER_WEB_USE_SKIA=true
    - cp -r build/web xournalpp-web-$VERSION
  artifacts:
    paths:
      - xournalpp-web-*

build:linux:
  stage: build
  image: snapcore/snapcraft:edge
  before_script:
    - ''
  script: |
    # required to upgrade ubuntu base due to incompatible libraries
    sed -i "s/xenial/focal/g" /etc/apt/sources.list
    apt update -qq
    apt install -y -qq wget tar unzip zip lib32stdc++6 lib32z1 git clang cmake ninja-build pkg-config libgtk-3-dev curl
    # flutter sdk setup
    git clone -b master https://github.com/flutter/flutter.git /flutter
    export PATH=$PATH:/flutter/bin
    flutter build linux
    mv build/linux/release/bundle xournalpp-mobile-$VERSION
  artifacts:
    paths:
      - xournalpp-mobile-*

build:snap:
  stage: build
  image: snapcore/snapcraft:edge
  before_script:
    - ''
  script: |
    # required to upgrade ubuntu base due to incompatible libraries
    sed -i "s/xenial/focal/g" /etc/apt/sources.list
    apt update -qq
    apt install -y -qq wget tar unzip zip lib32stdc++6 lib32z1 git clang cmake ninja-build pkg-config libgtk-3-dev curl
    # flutter sdk setup
    git clone -b master https://github.com/flutter/flutter.git /flutter
    export PATH=$PATH:/flutter/bin
    # ignore current snap version and set to pubspec version
    # "s/version\:\W\+[0-9]\+\.[0-9]\+\.[0-9]\+/version: $VERSION/g" or "s/[0-9]\+\.[0-9]\+\.[0-9]\+/$VERSION/g"
    sed -i "s/version\:\W\+[0-9]\+\.[0-9]\+\.[0-9]\+/version: $VERSION/g" snap/snapcraft.yaml
    echo $SNAPCRAFT_LOGIN_FILE | base64 --decode --ignore-garbage > snapcraft.login
    snapcraft login --with snapcraft.login
    set +o pipefail
    snapcraft
    mv *.snap xournalpp-mobile-$VERSION.snap
    snapcraft upload xournalpp-mobile-$VERSION.snap --release=stable
  artifacts:
    paths:
      - xournalpp-mobile-*.snap
  only:
      - tags
  except:
    - branches

pages:
  stage: deploy
  image: alpine:latest
  script:
    - mkdir public
    - cp -r build/web/* public/
  artifacts:
    paths:
      - public
  only:
    - master
