name: xournalpp
description: A port of the main features of Xournal++ to various Flutter platforms like Android, iOS and the Web.

publish_to: none

version: 1.1.6+22

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker_cross: ^4.1.1
  katex_flutter: ^4.0.0
  intl: ^0.16.1
  archive: ^2.0.13
  xml: ^4.2.0
  url_launcher: ^5.5.0
  # for Windows
  url_launcher_fde:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/flutter_plugins/url_launcher_fde
      ref: master
  transparent_image: ^1.0.0
  catcher: ^0.3.17
  receive_sharing_intent: ^1.4.0
  after_init: ^0.1.2
  flutter_dropzone: ^1.0.7
  shared_preferences: ^0.5.8
  flutter_absolute_path: 1.0.6
  matrix_gesture_detector: ^0.1.0
  vector_math: ^2.0.8
  dwds: ^6.0.0
  flutter_colorpicker: ^0.3.4
  package_info: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk:
      flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
   android: true
   ios: true
   image_path: "assets/xournalpp.png"
   image_path_ios: "assets/xournalpp-solid.png"
   image_path_android: "assets/xournalpp-adaptive.png"
   adaptive_icon_background: "#673ab7"
   adaptive_icon_foreground: "assets/xournalpp-android.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Open Sans
      fonts:
        - asset: fonts/Open Sans/OpenSans-Regular.ttf
        - asset: fonts/Open Sans/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/Open Sans/OpenSans-ExtraBold.ttf
          weight: 800
    - family: Glacial Indifference
      fonts:
        - asset: fonts/Glacial Indifference/GlacialIndifference-Regular.otf

flutter_intl:
  enabled: true
