name: xournalpp
description: A port of the main features of Xournal++ to various Flutter platforms like Android, iOS and the Web.

publish_to: none

version: 1.1.11+27

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker_cross: ^4.4.2
  katex_flutter: ^4.0.2+26
  intl: ^0.17.0
  archive: ^3.1.2
  xml: ^5.1.1
  url_launcher: ^6.0.4
  transparent_image: ^2.0.0
#  catcher: ^0.4.0
  receive_sharing_intent: ^1.4.5
  after_init: ^0.1.2
  flutter_dropzone: ^2.0.1
  shared_preferences: ^2.0.6
  flutter_absolute_path: 1.0.6
  matrix_gesture_detector: ^0.2.0-nullsafety.1
  vector_math: ^2.1.0
  dwds: ^11.0.2
  flutter_colorpicker: ^0.4.0
  package_info: ^2.0.2
  printing: ^5.2.1
  pdf: ^3.3.0
#  zefyr: ^0.12.0
#  notus: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk:
      flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
   android: true
   ios: true
   image_path: "assets/xournalpp.png"
   image_path_ios: "assets/xournalpp-solid.png"
   image_path_android: "assets/xournalpp-adaptive.png"
   adaptive_icon_background: "#673ab7"
   adaptive_icon_foreground: "assets/xournalpp-android.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Open Sans
      fonts:
        - asset: fonts/Open Sans/OpenSans-Regular.ttf
        - asset: fonts/Open Sans/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/Open Sans/OpenSans-ExtraBold.ttf
          weight: 800
    - family: Glacial Indifference
      fonts:
        - asset: fonts/Glacial Indifference/GlacialIndifference-Regular.otf

flutter_intl:
  enabled: true
